// AUTO-GENERATED by scripts/gen-messages.ts — do not edit.
// Run `bun run gen` to regenerate.
import { handle$cell_configure, type CellConfigureMessage } from "./_cell_configure.ts";
import { handle$cell_send, type CellSendMessage } from "./_cell_send.ts";
import { handle$close, type CloseMessage } from "./_close.ts";
import { handle$configure, type ConfigureMessage } from "./_configure.ts";
import { handle$data, type DataMessage } from "./_data.ts";
import { handle$error, type ErrorMessage } from "./_error.ts";
import { handle$prompt_configure, type PromptConfigureMessage } from "./_prompt_configure.ts";
import { handle$prompt_highlight, type PromptHighlightMessage } from "./_prompt_highlight.ts";
import { handle$sync, type SyncMessage } from "./_sync.ts";
import { handle$text, type TextMessage } from "./_text.ts";

/** Registry of message handlers, keyed by message `type`. */
export const handlers = {
    cell_configure: handle$cell_configure,
    cell_send: handle$cell_send,
    close: handle$close,
    configure: handle$configure,
    data: handle$data,
    error: handle$error,
    prompt_configure: handle$prompt_configure,
    prompt_highlight: handle$prompt_highlight,
    sync: handle$sync,
    text: handle$text,
} as const;

/** Union of every message type. */
export type IncomingDriverMessage = CellConfigureMessage | CellSendMessage | CloseMessage | ConfigureMessage | DataMessage | ErrorMessage | PromptConfigureMessage | PromptHighlightMessage | SyncMessage | TextMessage;
