// AUTO-GENERATED by scripts/gen-messages.ts — do not edit.
// Run `bun run gen` to regenerate.
import { handle$cell_configure, type CellConfigureMessage } from "./_cell_configure";
import { handle$cell_create, type CellCreateMessage } from "./_cell_create";

/** Registry of message handlers, keyed by message `type`. */
export const handlers = {
    cell_configure: handle$cell_configure,
    cell_create: handle$cell_create,
} as const;

/** Union of every message type. */
export type Message = CellConfigureMessage | CellCreateMessage;
