// AUTO-GENERATED by scripts/gen-messages.ts — do not edit.
// Run `bun run gen` to regenerate.

/** Message `type` names for driver incoming messages. */
export const incomingDriverMessageTypes = new Set<string>([
    "cell_configure",
    "cell_send",
    "close",
    "data",
    "echo",
    "error",
    "prompt_configure",
    "sync",
    "text",
]);

/** Message `type` names for driver outgoing messages. */
export const outgoingDriverMessageTypes = new Set<string>(["command", "parse", "signal", "sync"]);

/** Message `type` names for interface incoming messages. */
export const incomingInterfaceMessageTypes = new Set<string>([
    "signal",
    "user_command",
    "user_focus",
    "user_input",
]);

/** Message `type` names for interface outgoing messages. */
export const outgoingInterfaceMessageTypes = new Set<string>([
    "cell_command",
    "install_cell",
    "install_echo",
    "install_prompt",
    "prompt_submit",
    "update_status",
]);
