// AUTO-GENERATED by scripts/gen-messages.ts — do not edit.
// Run `bun run gen` to regenerate.

/** Message `type` names for driver incoming messages. */
export const incomingDriverMessageTypes = new Set<string>([
    "cell_configure",
    "cell_send",
    "close",
    "data",
    "echo",
    "error",
    "prompt_configure",
    "prompt_highlight",
    "sync",
    "text",
]);

/** Message `type` names for driver outgoing messages. */
export const outgoingDriverMessageTypes = new Set<string>([
    "command",
    "parse",
    "resize",
    "signal",
    "sync",
    "text",
]);

/** Message `type` names for interface incoming messages. */
export const incomingInterfaceMessageTypes = new Set<string>([
    "user_command",
    "user_focus",
    "user_input",
    "user_resize",
    "user_signal",
    "user_text",
]);

/** Message `type` names for interface outgoing messages. */
export const outgoingInterfaceMessageTypes = new Set<string>([
    "cell_command",
    "install_echo",
    "problem",
    "update_cell",
    "update_entry",
    "update_prompt",
]);
