// AUTO-GENERATED by scripts/gen-messages.ts — do not edit.
// Run `bun run gen` to regenerate.
import { handle$user_command, type UserCommandMessage } from "./_user_command.ts";
import { handle$user_focus, type UserFocusMessage } from "./_user_focus.ts";
import { handle$user_input, type UserInputMessage } from "./_user_input.ts";
import { handle$user_resize, type UserResizeMessage } from "./_user_resize.ts";
import { handle$user_signal, type UserSignalMessage } from "./_user_signal.ts";
import { handle$user_text, type UserTextMessage } from "./_user_text.ts";

/** Registry of message handlers, keyed by message `type`. */
export const handlers = {
    user_command: handle$user_command,
    user_focus: handle$user_focus,
    user_input: handle$user_input,
    user_resize: handle$user_resize,
    user_signal: handle$user_signal,
    user_text: handle$user_text,
} as const;

/** Union of every message type. */
export type IncomingInterfaceMessage = UserCommandMessage | UserFocusMessage | UserInputMessage | UserResizeMessage | UserSignalMessage | UserTextMessage;
