// AUTO-GENERATED by scripts/gen-messages.ts — do not edit.
// Run `bun run gen` to regenerate.
import { handle$user_focus, type UserFocusMessage } from "./_user_focus";
import { handle$user_prompt, type UserPromptMessage } from "./_user_prompt";

/** Registry of message handlers, keyed by message `type`. */
export const handlers = {
    user_focus: handle$user_focus,
    user_prompt: handle$user_prompt,
} as const;

/** Union of every message type. */
export type IncomingInterfaceMessage = UserFocusMessage | UserPromptMessage;
